export const USER_LOGGED_IN_ROOM = "USER_LOGGED_IN_ROOM"
export const USER_LOGGED_OUT_ROOM = "USER_LOGGED_OUT_ROOM"
export const LOADING_AUTH_ROOM = "LOADING_AUTH_ROOM"
export const AUTH_ROOM_LOADED = "AUTH_ROOM_LOADED"